# Generated by Django 3.0.3 on 2020-03-24 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('larps', '0002_player_shoulder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='character_assigment',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='uniform',
        ),
        migrations.AddField(
            model_name='bookings',
            name='larp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='larps.Larp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='run',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookings',
            name='weapon',
            field=models.BooleanField(default=False),
        ),
    ]
