# Generated by Django 3.0.3 on 2020-03-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('larps', '0004_auto_20200324_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='larps.BusStop'),
        ),
    ]
