# Generated by Django 3.0.3 on 2020-03-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larps', '0006_bookings_sleeping_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
