# Generated by Django 3.0.3 on 2020-03-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larps', '0009_player_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='comments',
            field=models.CharField(blank=True, default='no', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='comments',
            field=models.CharField(blank=True, default='no', max_length=200, null=True),
        ),
    ]
