# Generated by Django 3.0.3 on 2020-03-27 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('larps', '0010_auto_20200325_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='uniform',
        ),
        migrations.CreateModel(
            name='UniformSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('american_size', models.CharField(max_length=10)),
                ('european_size', models.CharField(max_length=10)),
                ('chest_min', models.IntegerField()),
                ('chest_max', models.IntegerField()),
                ('waist_min', models.IntegerField()),
                ('waist_max', models.IntegerField()),
                ('uniform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='larps.Uniform')),
            ],
        ),
        migrations.AddField(
            model_name='uniform',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='larps.Group'),
        ),
    ]
