# Generated by Django 3.0.3 on 2020-03-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larps', '0012_auto_20200327_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
