# Generated by Django 3.1.3 on 2020-11-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larps', '0014_auto_20201110_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniform',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
