# Generated by Django 3.1.3 on 2020-11-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larps', '0016_auto_20201115_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sleeve_length',
            field=models.IntegerField(default=0),
        ),
    ]
