# Generated by Django 3.1.3 on 2020-11-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larps', '0017_player_sleeve_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='height',
            new_name='arm_length',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='shoulder',
            new_name='body_length',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='sleeve_length',
            new_name='shoulder_length',
        ),
        migrations.AddField(
            model_name='player',
            name='torso_length',
            field=models.IntegerField(default=0),
        ),
    ]
