# Generated by Django 3.1.3 on 2020-11-21 20:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('larps', '0018_auto_20201121_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='PlayerMeasurement',
        ),
    ]
