# Generated by Django 3.1.3 on 2020-11-21 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larps', '0019_auto_20201121_2108'),
        ('larps', '0018_remove_bookings_weapon'),
    ]

    operations = [
    ]
