# Generated by Django 3.1.3 on 2020-12-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larps', '0021_remove_uniform_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='short_concept',
            new_name='concept',
        ),
        migrations.AddField(
            model_name='character',
            name='rank',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='sheet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='type',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
