# Generated by Django 3.1.3 on 2020-12-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('larps', '0022_auto_20201205_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='playermeasurement',
            name='gender',
        ),
        migrations.AddField(
            model_name='characterassigment',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='larps.gender'),
        ),
        migrations.AlterField(
            model_name='uniformsize',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='larps.gender'),
        ),
    ]
