# Generated by Django 3.1.3 on 2021-01-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larps', '0023_auto_20201206_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterassigment',
            name='discord_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
