# Generated by Django 3.1.3 on 2021-01-03 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larps', '0024_characterassigment_discord_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='type',
        ),
    ]
