# Generated by Django 3.1.3 on 2021-01-03 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larps', '0026_auto_20210103_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='weapon',
        ),
    ]
