# Generated by Django 3.1.4 on 2021-03-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larps', '0028_character_weapon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='comments',
            field=models.CharField(blank=True, default='no', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='character',
            name='concept',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='character',
            name='rank',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='character',
            name='sheet',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapon',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='characterassigment',
            name='discord_email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='charactertype',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='group',
            name='weapon',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='larp',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='uniform',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='uniformsize',
            name='american_size',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='uniformsize',
            name='european_size',
            field=models.CharField(max_length=500),
        ),
    ]
