# Generated by Django 3.2 on 2021-04-06 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('larps', '0029_auto_20210306_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermeasurement',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='larps.gender'),
        ),
    ]
