# Generated by Django 3.1.4 on 2021-05-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larps', '0030_playermeasurement_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='design_document',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='character',
            name='easy_read_sheet',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
